import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';
import { registerSW } from 'virtual:pwa-register';
import { SplashScreen } from '@capacitor/splash-screen';
import { renderApp } from './app.js';
import { guardStartup, installErrorBoundary } from './errorBoundary.js';
import { initMobileHandlers } from './mobile.js';

// Install first — everything below is then covered by the boundary.
installErrorBoundary();

// Register the Service Worker generated by vite-plugin-pwa
if ('serviceWorker' in navigator) {
  registerSW({ immediate: true });
}

guardStartup(() => {
  // Mount the app shell
  const container = document.getElementById('app');
  if (!container) throw new Error('Root #app element not found');
  renderApp(container);

  // Initialize Capacitor native mobile handlers (back button, lifecycle, wakelock)
  initMobileHandlers();
});

// Hide native splash screen seamlessly once UI is mounted
SplashScreen.hide().catch(() => {});
