import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';
import { registerSW } from 'virtual:pwa-register';
import { SplashScreen } from '@capacitor/splash-screen';
import { renderApp } from './app.js';

// Register the Service Worker generated by vite-plugin-pwa
if ('serviceWorker' in navigator) {
  registerSW({ immediate: true });
}

// Mount the app shell
const container = document.getElementById('app');
if (!container) throw new Error('Root #app element not found');
renderApp(container);

// Hide native splash screen seamlessly once UI is mounted
SplashScreen.hide().catch(() => {});
